name: Python formatting and tests

on:
  push:
    paths:
      - "**.py"

permissions:
  contents: "read"
  id-token: "write"

jobs:
  call-python-black:
    uses: calico/calico-github-actions/.github/workflows/python-black.yml@main
    permissions:
      contents: "write"
      id-token: "write"
  call-python-pytest-3-11:
    if: github.event.repository.name != 'github-template-python-library'
    uses: calico/calico-github-actions/.github/workflows/python-pytest.yml@main
    with:
      python-version: "3.11"
  run-python-ruff:
    uses: calico/calico-github-actions/.github/workflows/python-ruff.yml@main
